use crate::core::types::EditParams;

/// GPU-friendly representation of edit parameters.
/// Must match the WGSL struct layout with strict 16-byte alignment.
#[repr(C)]
#[derive(Copy, Clone, Debug, bytemuck::Pod, bytemuck::Zeroable)]
pub struct GpuEditParams {
    pub exposure: f32,
    pub contrast: f32,
    pub highlights: f32,
    pub shadows: f32,
    pub whites: f32,
    pub blacks: f32,
    pub vibrance: f32,
    pub saturation: f32,
    pub temperature: f32,
    pub tint: f32,
    padding1: f32,
    padding2: f32,
    pub wb_multipliers: [f32; 4],
    pub forward_matrix_0: [f32; 3],
    _padding3: f32,
    pub forward_matrix_1: [f32; 3],
    _padding4: f32,
    pub forward_matrix_2: [f32; 3],
    _padding5: f32,
    pub zoom: f32,
    pub pan_x: f32,
    pub pan_y: f32,
    pub cfa_pattern: u32,
    _pad_cfa_1: f32,
    _pad_cfa_2: f32,
    _pad_cfa_3: f32,
    _pad_cfa_4: f32,
    pub black_levels: [u32; 4],
    pub white_level: u32,
    _pad_end_1: f32,
    _pad_end_2: f32,
    _pad_end_3: f32,
    black_offsets: [f32; 4],
    black_phase_x: u32,
    black_phase_y: u32,
    luma_noise: f32,
    color_noise: f32,
    sharpening: f32,
    sharpen_masking: f32,
    rotation: f32,
    _pad_phase_1: f32,
    pub crop: [f32; 4],
    pub is_cropping: u32,
    pub has_dcp: u32,
    pub dcp_has_curve: u32,
    /// EXIF orientation (1/3/6/8) — per-image, set from ImageResources.
    pub orientation: u32,
}

impl From<&EditParams> for GpuEditParams {
    fn from(params: &EditParams) -> Self {
        Self {
            exposure: params.exposure,
            contrast: params.contrast,
            highlights: params.highlights,
            shadows: params.shadows,
            whites: params.whites,
            blacks: params.blacks,
            vibrance: params.vibrance,
            saturation: params.saturation,
            temperature: params.temperature,
            tint: params.tint,
            padding1: 0.0,
            padding2: 0.0,
            wb_multipliers: [1.0, 1.0, 1.0, 1.0],
            forward_matrix_0: [1.0, 0.0, 0.0],
            _padding3: 0.0,
            forward_matrix_1: [0.0, 1.0, 0.0],
            _padding4: 0.0,
            forward_matrix_2: [0.0, 0.0, 1.0],
            _padding5: 0.0,
            zoom: 1.0,
            pan_x: 0.0,
            pan_y: 0.0,
            cfa_pattern: 0,
            _pad_cfa_1: 0.0,
            _pad_cfa_2: 0.0,
            _pad_cfa_3: 0.0,
            _pad_cfa_4: 0.0,
            black_levels: [0, 0, 0, 0],
            white_level: 65535,
            _pad_end_1: 0.0,
            _pad_end_2: 0.0,
            _pad_end_3: 0.0,
            black_offsets: params.black_offsets,
            black_phase_x: params.black_phase_x,
            black_phase_y: params.black_phase_y,
            luma_noise: params.luma_noise,
            color_noise: params.color_noise,
            sharpening: params.sharpening,
            sharpen_masking: params.sharpen_masking,
            rotation: params.rotation,
            _pad_phase_1: 0.0,
            crop: params.crop,
            is_cropping: params.is_cropping,
            has_dcp: 0,
            dcp_has_curve: 0,
            orientation: 1,
        }
    }
}
