name: RawEditor CI & Release

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
    paths-ignore:
      - "README.md"
      - "LICENSE"

permissions:
  contents: write


jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Rust cache
        uses: Swatinem/rust-cache@v2

      - name: Build release
        run: cargo build --release

      - name: Prepare release directory (Linux)
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          APP=raw-editor
          VERSION=${GITHUB_REF_NAME}

          mkdir -p dist/$APP-linux

          cp target/release/$APP dist/$APP-linux/
          cp target/release/$APP.d dist/$APP-linux/ || true
          cp -r assets dist/$APP-linux/
          cp README.md dist/$APP-linux/ || true
          cp LICENSE dist/$APP-linux/ || true

          cd dist
          zip -r "$APP-linux-$VERSION.zip" "$APP-linux"

      - name: Prepare release directory (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $APP = "raw-editor"
          $VERSION = "${env:GITHUB_REF_NAME}"
          $OUT = "dist\$APP-windows"

          New-Item -ItemType Directory -Force -Path $OUT | Out-Null

          Copy-Item "target\release\$APP.exe" $OUT
          Copy-Item "assets" $OUT -Recurse
          Copy-Item "README.md" $OUT -ErrorAction SilentlyContinue
          Copy-Item "LICENSE" $OUT -ErrorAction SilentlyContinue

          Compress-Archive -Path $OUT -DestinationPath "dist\$APP-windows-$VERSION.zip"


      - name: Upload artifact (CI)
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-zip
          path: dist/*.zip

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
